services:
  game:
      build:
        context: .
        dockerfile: Dockerfile
      user: 1000:1000
      container_name: chess_server_game
      ports:
          - ${WSS_GAME_PORT}:${WSS_GAME_PORT}
      restart: always
      volumes:
          - ./:/usr/share/chess-server
          - /usr/share/chess-server/vendor
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      working_dir: /usr/share/chess-server
      command: ["php", "cli/workerman/game.php", "start", "--d"]
  data:
      build:
        context: .
        dockerfile: Dockerfile
      user: 1000:1000
      container_name: chess_server_data
      ports:
          - ${WSS_DATA_PORT}:${WSS_DATA_PORT}
      restart: always
      volumes:
          - ./:/usr/share/chess-server
          - /usr/share/chess-server/vendor
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      working_dir: /usr/share/chess-server
      command: ["php", "cli/workerman/data.php", "start", "--d"]
  binary:
      build:
        context: .
        dockerfile: Dockerfile
      user: 1000:1000
      container_name: chess_server_binary
      ports:
          - ${WSS_BINARY_PORT}:${WSS_BINARY_PORT}
      restart: always
      volumes:
          - ./:/usr/share/chess-server
          - /usr/share/chess-server/vendor
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      working_dir: /usr/share/chess-server
      command: ["php", "cli/workerman/binary.php", "start", "--d"]
  auth:
      build:
        context: .
        dockerfile: Dockerfile
      user: 1000:1000
      container_name: chess_server_auth
      ports:
          - ${WSS_AUTH_PORT}:${WSS_AUTH_PORT}
      restart: always
      volumes:
          - ./:/usr/share/chess-server
          - /usr/share/chess-server/vendor
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      working_dir: /usr/share/chess-server
      command: ["php", "cli/workerman/auth.php", "start", "--d"]
